name: stockregressioncs449
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - statsmodels
  - pytorch
  - tqdm
  - matplotlib
  - pip
  - scikit-learn
  - xgboost
  - ipykernel
  - pip:
    - yfinance
